--- #YAML:1.0
name:                Text-vFile-toXML
version:             0.02
abstract:            Convert vFiles into equivalent XML
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Test::More:                    0
    Text::vFile::asData:           0
    XML::Quick:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Darren Kulp <kulp@cpan.org>
