--- 
abstract: Convert vFiles into equivalent XML
author: 
  - Darren Kulp, C<< <kulp at cpan.org> >>
build_requires: 
  Test::More: 0.42
  Text::vFile::asData: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: bsd
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Text-vFile-toXML
no_index: 
  directory: 
    - inc
    - t
requires: 
  Text::vFile::asData: 0
  XML::Quick: 0
version: 0.04
